#!/bin/zsh
# Verification Pass 4 — Reproducibility & completeness for Figure 3
#
# Move all generated outputs to a backup dir, re-run the entire pipeline
# from scratch, verify outputs are regenerated and match the backup byte-for-byte.

set -u
cd /Users/petecastaldi/claude_projects/nmd/figures/multipanel/figure3_isopair_and_ptc

BACKUP_DIR=".verify_pass4_backup"
rm -rf "$BACKUP_DIR"
mkdir -p "$BACKUP_DIR/data"

# ---- 1. Move existing outputs to backup ----
echo "[1] Backing up current outputs..."
for f in data/panel*.tsv; do
  [ -f "$f" ] && cp "$f" "$BACKUP_DIR/$f"
done
for f in figure3_panel*.pdf figure3_panel*.png; do
  [ -f "$f" ] && cp "$f" "$BACKUP_DIR/$f"
done
n_tsv_backup=$(ls $BACKUP_DIR/data/*.tsv 2>/dev/null | wc -l | tr -d ' ')
n_pdf_backup=$(ls $BACKUP_DIR/*.pdf 2>/dev/null | wc -l | tr -d ' ')
echo "  Backed up: $n_tsv_backup TSVs, $n_pdf_backup PDFs"

# ---- 2. Delete originals to force regeneration ----
echo "[2] Removing originals..."
rm -f data/panel*.tsv figure3_panel*.pdf figure3_panel*.png

# ---- 3. Re-run data_export.R ----
echo "[3] Re-running data_export.R..."
Rscript data_export.R > "$BACKUP_DIR/data_export.log" 2>&1
rc=$?
if [ $rc -ne 0 ]; then
  echo "  FAIL: data_export.R exited with code $rc"
  tail -10 "$BACKUP_DIR/data_export.log"
  exit 1
fi
echo "  PASS: data_export.R ran successfully"

# ---- 4. Verify TSVs regenerated ----
echo "[4] Checking regenerated TSVs..."
expected_tsvs=(panelB_sequence_similarity.tsv panelC_event_prevalence.tsv panelD_stop_codon_distance.tsv panelE_ptc_event_attribution.tsv panelF_mechanism_breakdown.tsv)
all_ok=1
for f in $expected_tsvs; do
  if [ -f "data/$f" ]; then
    if diff -q "data/$f" "$BACKUP_DIR/data/$f" > /dev/null 2>&1; then
      echo "  PASS: data/$f regenerated byte-identically"
    else
      lines_new=$(wc -l < "data/$f" | tr -d ' ')
      lines_bak=$(wc -l < "$BACKUP_DIR/data/$f" | tr -d ' ')
      echo "  WARN: data/$f regenerated but content differs (new=$lines_new lines, backup=$lines_bak lines)"
      all_ok=0
    fi
  else
    echo "  FAIL: data/$f not regenerated"
    all_ok=0
  fi
done

# ---- 5. Re-render all panels ----
echo "[5] Re-rendering panels..."
PY=~/miniforge3/bin/python
for f in figure3_panel*.py; do
  out=$($PY "$f" 2>&1)
  rc=$?
  if [ $rc -eq 0 ]; then
    echo "  PASS: $f rendered"
  else
    echo "  FAIL: $f failed: $out"
    all_ok=0
  fi
done

# ---- 6. Verify panel PDFs exist + validate clean ----
echo "[6] Validating rendered PDFs..."
for f in figure3_panel*.pdf; do
  out=$($PY /Users/petecastaldi/claude_projects/nmd/figures/lib/validate_figure_layout.py "$f" 2>&1)
  if [ -z "$out" ]; then
    echo "  PASS: $f validator clean"
  else
    echo "  WARN: $f validator output: $out"
  fi
done

# ---- 7. Source-file existence cross-check ----
echo "[7] Checking referenced inputs exist..."
inputs=(
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/profiles_c2_allsamples.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/profiles_c4_allsamples.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/cds.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/ptc.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/structures.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/gene_map.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/nmd_classification.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/analysis_cache/ref_atg_analysis.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/analysis_cache/fc_c2_allsamples.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/analysis_cache/fw_c2_allsamples.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/analysis_cache/div_c2_allsamples.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/data_mashr/analysis_cache/div_c4_allsamples.rds
  /Users/petecastaldi/claude_projects/nmd/results/isoform_transitions/Version_6.0/isopair_wrapper/analysis_functions.R
)
for f in $inputs; do
  if [ -f "$f" ]; then
    echo "  PASS: $(basename $f)"
  else
    echo "  FAIL: $f missing"
    all_ok=0
  fi
done

# ---- 8. Methodology file → script cross-reference check ----
echo "[8] Checking methodology files reference real scripts..."
for m in figure3_panel*_methodology.md; do
  panel_letter=$(echo $m | sed 's/figure3_panel\(.\)_methodology.md/\1/')
  expected_py="figure3_panel${panel_letter}_*.py"
  matches=$(ls $expected_py 2>/dev/null | wc -l | tr -d ' ')
  if [ $matches -ge 1 ]; then
    echo "  PASS: $m references existing script"
  else
    echo "  FAIL: $m references nonexistent script pattern $expected_py"
    all_ok=0
  fi
done

# ---- Summary ----
echo ""
echo "================================================================"
if [ $all_ok -eq 1 ]; then
  echo "Pass 4 verdict: PASS — pipeline fully reproducible"
else
  echo "Pass 4 verdict: SOME ISSUES — see warnings above"
fi
echo "================================================================"
