suppressMessages({library(mashr); library(ashr)})
fit2 <- readRDS("/tmp/ct_de_fit2.rds")
bhat <- fit2$coefficients; shat <- fit2$coefficients / fit2$t
fin <- apply(shat, 1, function(x) all(is.finite(x) & x > 0))
bhat <- bhat[fin,,drop=FALSE]; shat <- shat[fin,,drop=FALSE]
d0 <- mash_set_data(Bhat=bhat, Shat=shat)
strong <- get_significant_results(mash_1by1(d0), thresh=0.05)
set.seed(42)
idx <- sample(seq_len(nrow(bhat)), min(20000, nrow(bhat)))
Vhat <- estimate_null_correlation_simple(mash_set_data(Bhat=bhat[idx,,drop=FALSE], Shat=shat[idx,,drop=FALSE]))
md <- mash_set_data(Bhat=bhat, Shat=shat, V=Vhat)
U_pca <- if (length(strong)>=5) cov_pca(md, npc=min(5,ncol(bhat)-1), subset=strong) else list()
m <- mash(md, Ulist=c(U_pca, cov_canonical(md)), outputlevel=2)
pm <- get_pm(m); lf <- get_lfsr(m)
cat("claim: LAE 28,930 | AT2 22,131 | MV 21,429 | FB 18,422\n\n")
cat("-- MARKER rule (Methods): lfsr<0.05 & posterior mean logFC > 1 --\n")
for (cn in colnames(lf)) cat(sprintf("   %-12s %6d\n", cn, sum(lf[,cn]<0.05 & pm[,cn]>1)))
